theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  plausible: aliceetlescryptotrolls.org
  logo:
    header: "/assets/images/alice.png"
  summary:
    position: hero
  image_sizes:
    design_system:
      lightbox: 
        disabled: true
  debug:
     productionUrl: "https://www.aliceetlescryptotrolls.org"