theme: osuny
_merge: deep
params:
  plausible: aliceetlescryptotrolls.org
  logo:
    header: "/assets/images/alice.png"
  summary:
    position: hero
  components:
    lightbox:
      disabled: true
  debug:
     productionUrl: "https://www.aliceetlescryptotrolls.org"
  home:
    head:
      title: site
